users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCowsR4NqUOjx/vsZOxCLzC56jabWeni7xPAgujjtqWxcOA1D3ch66iKRr5T5UQ4CsAkfk5lqCt8g7oIwBxQx/rJ7ySyKOh0mrp34Woftm6Yi2ooB6itgEu7gkS5xvzGYvSOXvJrD2r3XHark0CVNdo7EFWJGhebxAc5rMkPrCtKLuUXb+JW/oT9Unibssw0hQhB5KTkP9FCDLEOA2x/VK340hj5vIu+xWcMd9V60dTsDxt96PjtoKK5CQytNALXeAwxZGuxYO87TlD5wfD0D3Mcviiw5kxR/IwyM0zOTyqBBdpJ9Sh372UN5vPHRyCKoDmISgOvh+wapGICVYgB+BcOo4lZHd9WwO/ZhTeZMVYCZYkZem2J7zD2vV5877RYMMUkZYQ+HZ95JRYAN8ojXfgmdH3x/MMnMccQZsAS0v557fnvPd2MJM1jMfZQM0q8hteK45atha/E/pGXLGivdzqx/JqZXfS5c4FJGS3XZSpEkdzhbCn2UxfYkvrt4lraIhg+pXnDLwle8o/nw+8Y/V0fBunm885nH9nMT2eYSmk29/GfVuy3aLdT2wFB1P4UOnBEImxyaIrFPUDzSqP8z+73bw8xdnOQLgi4ZAmIzMRkIr5W1Jef0/JOITvNdJpqR94Me74Lxz4XZKrc9CsLwIcut+SiyC6QYK3T/dSf/UxNw== akimsheremetev@gmail.com

