---
- name: kibana container
  hosts: kibana
  become: yes
  vars:
    ansible_ssh_user: "user"
  tasks:
    - name: run kibana docker container
      docker_container:
        name: kibana01
        image: elastic/kibana:9.2.0
        state: started
        ports:
          - "5601:5601"
        network_mode: host
        restart_policy: always
        env:
          ELASTICSEARCH_HOSTS: "http://10.0.1.27:9200"
