---
- name: test
  gather_facts: false
  hosts: webservers
  vars:
    ansible_ssh_user: user
  become: yes

  tasks:
    - name: create test file
      copy:
        dest: /tmp/test
        content: "success"
